# Generated by Django 5.0.4 on 2024-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usuario_direccion_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Articulo/'),
        ),
    ]
