# Generated by Django 5.0.4 on 2024-06-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_articulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
    ]
